version: '2.1'

services:


 db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    network_mode: "host"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
 node:
    image: "node:7.6"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./Mobius-master:/home/node/app
    network_mode: "host"
    expose:
      - "8081"
    command: "node mobius"
    depends_on:
            db:
                condition: service_healthy
 mqtt:
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
    network_mode: "host"
    volumes:
      - ./etc/mosquitto:/etc/mosquitto:ro
      - ./var/log/mosquitto:/var/log/mosquitto:rw
    depends_on:
            db:
                condition: service_healthy
